config/routes.rb
Gemcutter::Application.routes.draw do
  ################################################################################
  # Root

  root :to => 'home#index'

  ################################################################################
  # API v1

  namespace :api do
    namespace :v1 do
      resource :api_key, :only => :show do
        put :reset
      end
      resources :profiles, :only => :show
      resources :downloads, :only => :index do
        get :top, :on => :collection
        get :all, :on => :collection
      end
      constraints :id => Patterns::ROUTE_PATTERN, :format => /json|xml|yaml/ do
        get 'owners/:handle/gems(.:format)', :to => 'owners#gems', :as => 'owners_gems', :constraints => {:handle => Patterns::ROUTE_PATTERN}

        # In Rails 3.1, the following line can be replaced with:
        # resources :downloads, :only => :show, :format => true
        get 'downloads/:id.:format', :to => 'downloads#show', :as => 'download'
        # In Rails 3.1, the next TWO lines can be replaced with:
        # resources :versions, :only => :show, :format => true do
        get 'versions/:id.:format', :to => 'versions#show', :as => 'version'
        resources :versions, :only => :show do
          member do
            # In Rails 3.1, the following line can be replaced with:
            # get :reverse_dependencies, :format => true
            get 'reverse_dependencies.:format', :to => 'versions#reverse_dependencies', :as => 'reverse_dependencies'
          end

          member do
            get 'latest.json', :to => 'versions#latest', :as => 'latest'
          end

          # In Rails 3.1, the next TWO lines can be replaced with:
          # resources :downloads, :only => :show, :controller => 'versions/downloads', :format => true do
          get 'downloads.:format', :to => 'versions/downloads#index', :as => 'downloads'
          resources :downloads, :only => :index, :controller => 'versions/downloads' do
            collection do
              # In Rails 3.1, the following line can be replaced with:
              # get :search, :format => true
              get 'search.:format', :to => 'versions/downloads#search', :as => 'search'
            end
          end
        end
      end

      resources :dependencies, :only => :index

      resources :rubygems, :path => 'gems', :only => [:create, :show, :index], :id => Patterns::LAZY_ROUTE_PATTERN, :format => /json|xml|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank
          put :unyank
        end
        constraints :rubygem_id => Patterns::ROUTE_PATTERN do
          resource :owners, :only => [:show, :create, :destroy]
        end
      end

      resource :activity, :only => [], :format => /json|xml|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, :only => :show

      resources :web_hooks, :only => [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  ################################################################################
  # API v0

  scope :to => 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset'

    post 'gems'
    get  'gems/:id.json'

    scope :path => 'gems/:rubygem_id' do
      put  'migrate'
      post 'migrate'
      get    'owners(.:format)'
      post   'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI

  resource  :search,    :only => :show
  resource  :dashboard, :only => :show
  resources :profiles,  :only => :show
  resource  :profile,   :only => [:edit, :update]
  resources :stats,     :only => :index, :constraints => RecoveryMode

  resources :rubygems, :only => :index, :path => 'gems' do
    constraints :rubygem_id => Patterns::ROUTE_PATTERN do
      resource  :subscription, :only => [:create, :destroy]
      resources :versions,     :only => :index
    end
  end

  constraints :id => Patterns::ROUTE_PATTERN do
    resources :rubygems, :path => 'gems', :only => [:show, :edit, :update] do

      constraints :rubygem_id => Patterns::ROUTE_PATTERN do
        resources :versions, :only => :show
      end
    end
  end

  ################################################################################
  # Clearance Overrides

  resource :session, :only => [:create, :destroy]

  match 'sign_out' => 'sessions#destroy', :via => :delete, :as => 'sign_out'

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:create, :edit, :update]
  end

end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < Api::BaseController
  respond_to :json, :only => [:show]

  def show
    respond_with User.find_by_slug!(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :redirect_to_root, :unless => :signed_in?, :except => :show

  def edit
  end

  def show
    @user           = User.find_by_slug!(params[:id])
    rubygems        = @user.rubygems_downloaded
    @rubygems       = rubygems.slice!(0, 10)
    @extra_rubygems = rubygems
  end

  def update
    if current_user.update_attributes(params[:user])
      if current_user.email_reset
        sign_out
        flash[:notice] = "You will receive an email within the next few minutes. " <<
                         "It contains instructions for reconfirming your account with your new email address."
        redirect_to root_path
      else
        flash[:notice] = "Your profile was updated."
        redirect_to edit_profile_path
      end
    else
      render :edit
    end
  end
end

app/views/profiles/_rubygem.html.erb
<li class="<%= "small" unless graph %>">
  <a href="<%= rubygem_path(rubygem) %>" class="profile-rubygem">
    <%= rubygem.name %>
    <em><%= rubygem.versions.most_recent %></em>
  </a>
  <% unless Rails.env.recovery? %>
    <a href="#" class="profile-downloads">
      <div><%= t('download_count', :count => content_tag(:span, number_with_delimiter(rubygem.downloads))).html_safe %></div>
    </a>
    <% if graph %>
      <div id="graph-<%= rubygem.id %>" class="profile-graph">
      </div>
    <% end %>
  <% end %>
</li>

app/views/profiles/edit.html.erb
<% @title = t('.title') %>

<%= form_for current_user, :url => {:controller => 'profiles', :action => 'update'} do |form| %>
  <%= form.error_messages %>

  <div class="avatar_field">
    <%= form.label :avatar %>
    <%= gravatar(60) %>
    <%= link_to 'Change', 'http://www.gravatar.com' %>
  </div>

  <div class="text_field">
    <%= form.label :handle %>
    <%= form.text_field :handle %>
  </div>

  <div class="text_field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="profile-checkbox">
    <%= form.check_box :hide_email %>
    <%= form.label :hide_email, "Hide email in public profile"%>
  </div>

  <div class="text_field">
    <%= form.label :gittip_username %>
    <%= link_to "What's this?", "https://www.gittip.com/about/" %>
    <%= form.text_field :gittip_username %>
  </div>

  <div class="submit_field">
    <%= form.submit "Update", :data => {:disable_with => t('form_disable_with')} %>
  </div>

  <h3><%= t '.reset_password.title' %></h3>
  <p><%= t('.reset_password.text', :link => link_to(t('.reset_password.link_text'), new_password_url)).html_safe %></p>

  <h3><%= t '.api_access.title' %></h3>
  <p>
    <%= t('.api_access.key_is', :key => content_tag(:strong, current_user.api_key)).html_safe %>
  </p>
  <p>
    <%= t('.api_access.credentials', :gem_credentials_file => content_tag(:code, '~/.gem/credentials'),
                                     :gem_commands_link => link_to(t('.api_access.link_text'), page_url('gem_docs'))).html_safe %>
  </p>
<pre><code>curl -u <%= current_user.name %> https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials; chmod 0600 ~/.gem/credentials</code></pre>

<% end %>

<p><%= button_to t('.api_access.reset'), reset_api_v1_api_key_path, :method => :put, :data => {:confirm => t('.api_access.confirm_reset')} %></p>

app/views/profiles/show.html.erb
<% content_for :title do %>
  <div id="avatar-frame">
    <%= gravatar(64, "profile_gravatar", @user) %>
  </div>
  <div id="profile-info">
    <h2 id="profile-name"><%= link_to @user.display_handle, profile_path(@user.display_id) %></h2>
    <% unless @user.hide_email %>
      <h3 id="profile-email"><%= mail_to @user.email, "email", :encode => "hex" %></h3>
    <% end %>
    <h3 id="profile-gittip"><%= link_to "gittip", @user.gittip_url unless @user.gittip_username.blank? %></h3>
    <h3 id="profile-gems-count"><%= @user.total_rubygems_count.to_s %> <%= "gem".pluralize(@user.total_rubygems_count) %></h3>
  </div>
  <div id="downloads-ego">
    <% if @user == current_user %>
      <%= link_to "Edit Profile", edit_profile_path, :id => "edit-profile" %>
    <% end %>
    <% unless Rails.env.recovery? %>
      <h5 id="downloads">Downloads</h5>
      <div id="downloads_count">
        <div><strong><%= number_with_delimiter(@user.total_downloads_count) %></strong> all time</div>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :javascript do %>
  <%= javascript_include_tag "raphael", "g.raphael", "g.bar" %>
  <script type="text/javascript">
    $(document).ready(function() {
      var dates = <%= Rubygem.monthly_short_dates.to_json.html_safe %>;
      <% @rubygems.each do |rubygem| %>
        $.data(document.body, "graph-<%= rubygem.id %>", <%= rubygem.monthly_downloads.to_json.html_safe %>);
      <% end %>

      $(".profile-graph").each(function() {
        var id   = $(this).attr("id"),
            r    = Raphael(id),
            fin  = function () {
              var currentDate = dates[Math.floor(this.bar.x / 22 - 1)];
              this.flag = r.g.popup(this.bar.x, this.bar.y, currentDate + ": " + this.bar.value || "0").insertBefore(this);
            },
            fout = function () {
              this.flag.animate({opacity: 0}, 300, function () {this.remove();});
            };

        r.g.barchart(15, 9, 655, 125,
          [ $.data(document.body, id) ],
          { type: "soft", colors : { 0 : "rgb(200, 164, 164)" } }
        ).hover(fin, fout);
      });
    });
  </script>
<% end %>

<div id="profile">
  <div class="profile-list">
    <ol>
      <%= render :partial => 'rubygem', :collection => @rubygems + @extra_rubygems, :locals => {:graph => false}  %>
    </ol>
  </div>
</div>