config/routes.rb
Gemcutter::Application.routes.draw do
  ################################################################################
  # Root

  root :to => 'home#index'

  ################################################################################
  # API v1

  namespace :api do
    namespace :v1 do
      resource :api_key, :only => :show do
        put :reset
      end
      resources :profiles, :only => :show
      resources :downloads, :only => :index do
        get :top, :on => :collection
        get :all, :on => :collection
      end
      constraints :id => Patterns::ROUTE_PATTERN, :format => /json|xml|yaml/ do
        get 'owners/:handle/gems(.:format)', :to => 'owners#gems', :as => 'owners_gems', :constraints => {:handle => Patterns::ROUTE_PATTERN}

        # In Rails 3.1, the following line can be replaced with:
        # resources :downloads, :only => :show, :format => true
        get 'downloads/:id.:format', :to => 'downloads#show', :as => 'download'
        # In Rails 3.1, the next TWO lines can be replaced with:
        # resources :versions, :only => :show, :format => true do
        get 'versions/:id.:format', :to => 'versions#show', :as => 'version'
        resources :versions, :only => :show do
          member do
            # In Rails 3.1, the following line can be replaced with:
            # get :reverse_dependencies, :format => true
            get 'reverse_dependencies.:format', :to => 'versions#reverse_dependencies', :as => 'reverse_dependencies'
          end

          member do
            get 'latest.json', :to => 'versions#latest', :as => 'latest'
          end

          # In Rails 3.1, the next TWO lines can be replaced with:
          # resources :downloads, :only => :show, :controller => 'versions/downloads', :format => true do
          get 'downloads.:format', :to => 'versions/downloads#index', :as => 'downloads'
          resources :downloads, :only => :index, :controller => 'versions/downloads' do
            collection do
              # In Rails 3.1, the following line can be replaced with:
              # get :search, :format => true
              get 'search.:format', :to => 'versions/downloads#search', :as => 'search'
            end
          end
        end
      end

      resources :dependencies, :only => :index

      resources :rubygems, :path => 'gems', :only => [:create, :show, :index], :id => Patterns::LAZY_ROUTE_PATTERN, :format => /json|xml|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank
          put :unyank
        end
        constraints :rubygem_id => Patterns::ROUTE_PATTERN do
          resource :owners, :only => [:show, :create, :destroy]
        end
      end

      resource :activity, :only => [], :format => /json|xml|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, :only => :show

      resources :web_hooks, :only => [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  ################################################################################
  # API v0

  scope :to => 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset'

    post 'gems'
    get  'gems/:id.json'

    scope :path => 'gems/:rubygem_id' do
      put  'migrate'
      post 'migrate'
      get    'owners(.:format)'
      post   'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI

  resource  :search,    :only => :show
  resource  :dashboard, :only => :show
  resources :profiles,  :only => :show
  resource  :profile,   :only => [:edit, :update]
  resources :stats,     :only => :index, :constraints => RecoveryMode

  resources :rubygems, :only => :index, :path => 'gems' do
    constraints :rubygem_id => Patterns::ROUTE_PATTERN do
      resource  :subscription, :only => [:create, :destroy]
      resources :versions,     :only => :index
    end
  end

  constraints :id => Patterns::ROUTE_PATTERN do
    resources :rubygems, :path => 'gems', :only => [:show, :edit, :update] do

      constraints :rubygem_id => Patterns::ROUTE_PATTERN do
        resources :versions, :only => :show
      end
    end
  end

  ################################################################################
  # Clearance Overrides

  resource :session, :only => [:create, :destroy]

  match 'sign_out' => 'sessions#destroy', :via => :delete, :as => 'sign_out'

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:create, :edit, :update]
  end

end

app/controllers/api/v1/rubygems_controller.rb
class Api::V1::RubygemsController < Api::BaseController
  skip_before_filter :verify_authenticity_token, :only => [:create, :yank, :unyank]

  before_filter :authenticate_with_api_key, :only => [:index, :create, :yank, :unyank]
  before_filter :verify_authenticated_user, :only => [:index, :create, :yank, :unyank]
  before_filter :find_rubygem,              :only => [:show]
  before_filter :find_rubygem_by_name,      :only => [:yank, :unyank]
  before_filter :validate_gem_and_version,  :only => [:yank, :unyank]

  respond_to :json, :xml, :yaml, :on => [:index, :show, :latest, :just_updated]

  def index
    @rubygems = current_user.rubygems.with_versions
    respond_with(@rubygems, :yamlish => true)
  end

  def show
    if @rubygem.hosted? and @rubygem.public_versions.indexed.count.nonzero?
      respond_with(@rubygem, :yamlish => true)
    else
      render :text => "This gem does not exist.", :status => :not_found
    end
  end

  def create
    gemcutter = Pusher.new(current_user, request.body, request.host_with_port)
    gemcutter.process
    render :text => gemcutter.message, :status => gemcutter.code
  end

  def yank
    if @version.indexed?
      @version.yank!
      render :text => "Successfully yanked gem: #{@version.to_title}"
    else
      render :text => "The version #{params[:version]} has already been yanked.", :status => :unprocessable_entity
    end
  end

  def unyank
    if !@version.indexed?
      @version.unyank!
      render :text => "Successfully unyanked gem: #{@version.to_title}"
    else
      render :text => "The version #{params[:version]} is already indexed.", :status => :unprocessable_entity
    end
  end

  def reverse_dependencies
    rubygems = Rubygem.reverse_dependencies(params[:id])

    respond_with(rubygems.map(&:name), :yamlish => true)
  end

  private

  def validate_gem_and_version
    if !@rubygem.hosted?
      render :text => "This gem does not exist.", :status => :not_found
    elsif !@rubygem.owned_by?(current_user)
      render :text => "You do not have permission to yank this gem.", :status => :forbidden
    else
      begin
        slug = params[:platform].blank? ? params[:version] : "#{params[:version]}-#{params[:platform]}"
        @version = Version.find_from_slug!(@rubygem, slug)
      rescue ActiveRecord::RecordNotFound
        render :text => "The version #{params[:version]} does not exist.", :status => :not_found
      end
    end
  end
end

app/controllers/rubygems_controller.rb
class RubygemsController < ApplicationController
  before_filter :redirect_to_root, :only => [:edit, :update], :unless => :signed_in?
  before_filter :find_rubygem, :only => [:edit, :update, :show]
  before_filter :load_gem, :only => [:edit, :update]

  def index
    respond_to do |format|
      format.html do
        @letter = Rubygem.letterize(params[:letter])
        @gems   = Rubygem.letter(@letter).paginate(:page => params[:page])
      end
      format.atom do
        @versions = Version.published(20)
        render 'versions/feed'
      end
    end
  end

  def show
    @latest_version = @rubygem.versions.most_recent
    @versions       = @rubygem.public_versions(5)
  end

  def edit
  end

  def update
    if @linkset.update_attributes(params[:linkset])
      redirect_to rubygem_path(@rubygem)
      flash[:success] = "Gem links updated."
    else
      render :edit
    end
  end

protected

  def load_gem
    if !@rubygem.owned_by?(current_user)
      flash[:warning] = "You do not have permission to edit this gem."
      redirect_to root_url
    end

    @linkset = @rubygem.linkset
  end
end

app/helpers/rubygems_helper.rb
module RubygemsHelper
  def formatted_licenses(license_names)
    if license_names.blank?
      t(".no_licenses")
    else
      Array(license_names).join ", "
    end
  end

  def link_to_page(text, url)
    link_to(text, url, :rel => 'nofollow') if url.present?
  end

  def link_to_directory
    ("A".."Z").map { |letter| link_to(letter, rubygems_path(:letter => letter)) }.join
  end

  def simple_markup(text)
    if text =~ /^==+ [A-Z]/
      RDoc::Markup.new.convert(text, RDoc::Markup::ToHtml.new).html_safe
    else
      content_tag :p, text
    end
  end

  def subscribe_link(rubygem)
    if signed_in?
      subscribe = link_to 'Subscribe', rubygem_subscription_path(rubygem),
        :remote => true,
        :method => :post,
        :id     => 'subscribe',
        :class  => 'toggler',
        :style  => rubygem.subscribers.find_by_id(current_user.try(:id)) ? 'display:none' : 'display:inline-block'
    else
      link_to 'Subscribe', sign_in_path, :id => :subscribe, :class => :toggler
    end
  end

  def unsubscribe_link(rubygem)
    if signed_in?
      link_to 'Unsubscribe', rubygem_subscription_path(rubygem),
        :remote  => true,
        :method  => :delete,
        :id    => 'unsubscribe',
        :class => :toggler,
        :style => rubygem.subscribers.find_by_id(current_user.try(:id)) ? 'display:inline-block' : 'display:none'
    end
  end

  def atom_link(rubygem)
    link_to 'RSS', rubygem_versions_path(rubygem, format: 'atom'), :id => :rss
  end

  def download_link(version)
    link_to "Download", "/downloads/#{version.full_name}.gem", :id => :download
  end

  def gittip_link(rubygem)
    link_to "Gittip", rubygem.gittip_url, :id => :gittip
  end

  def documentation_link(version, linkset)
    link_to 'Documentation', documentation_path(version), :id => :docs if linkset.nil? ||
      linkset.docs.blank?
  end

  def documentation_path(version)
    "http://rubydoc.info/gems/#{version.rubygem.name}/#{version.number}/frames"
  end

  def badge_link(rubygem)
    badge_url = "http://badge.fury.io/rb/#{rubygem.name}/install"
    link_to "Badge", badge_url, :id => :badge
  end

  def stats_options(rubygem)
    [
      ['Overview', rubygem_stats_path(rubygem)],
      *rubygem.versions.sort.reverse.map do |version|
        [version.slug, rubygem_version_stats_path(rubygem, version.slug)]
      end
    ]
  end

  def links_to_owners(rubygem)
    rubygem.owners.sort_by(&:id).map do |owner|
      link_to gravatar(48, "gravatar-#{owner.id}", owner), profile_path(owner.display_id),
        :alt => owner.display_handle, :title => owner.display_handle
    end.join.html_safe
  end

  def nice_date_for(time)
    time.to_date.to_formatted_s(:long)
  end

  def show_all_versions_link?(rubygem)
    rubygem.versions_count > 5 || rubygem.yanked_versions?
  end

end

app/views/rubygems/_clippy.html.erb
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
        width="110"
        id="<%= embed %>" >
  <param name="movie" value="/<%= embed %>.swf"/>
  <param name="allowScriptAccess" value="always" />
  <param name="quality" value="high" />
  <param name="scale" value="noscale" />
  <param NAME="FlashVars" value="text=<%= text %>">
  <param name="wmode" value="transparent">
  <embed src="/<%= embed %>.swf"
         width="110"
         height="24"
         name="clippy"
         quality="high"
         allowScriptAccess="always"
         type="application/x-shockwave-flash"
         pluginspage="http://www.macromedia.com/go/getflashplayer"
         FlashVars="text=<%= text %>"
         wmode="transparent"
  />
</object>

app/views/rubygems/_dependencies.html.erb
<% if dependencies.present? && @latest_version.indexed %>
  <div class="dependencies" id="<%= dependencies.first.scope %>_dependencies">
    <h5><%= t '.header', :title => dependencies.first.scope.titleize %></h5>
    <ol>
    <% dependencies.each do |dependency| %>
      <li>
        <% if rubygem = dependency.rubygem %>
          <%= link_to rubygem_path(rubygem) do %>
            <strong><%= rubygem.name %></strong> <%= dependency.clean_requirements %>
          <% end %>
        <% else %>
          <strong><%= dependency.name %></strong> <%= dependency.clean_requirements %>
        <% end %>
      </li>
    <% end %>
    </ol>
  </div>
<% end %>

app/views/rubygems/_ruby_version.html.erb
<% if ruby_version.present? %>
  <div class="dependencies" id="ruby_dependency">
    <h5>Ruby Dependency</h5>
    <ol>
      <li>
        <%= ruby_version %>
      </li>
    </ol>
  </div>
<% end %>

app/views/rubygems/_rubygem.html.erb
<li>
  <%= download_count rubygem %>
  <a href="<%= rubygem_path(rubygem) %>">
    <strong><%= rubygem %></strong>
    <%= short_info(rubygem.versions.most_recent) %>
  </a>
</li>

app/views/rubygems/edit.html.erb
<% @title = t('.title') %>
<% @subtitle = t('.subtitle', :gem => @rubygem.name) %>
<p><%= t '.other_fields_notice' %></p>
<%= error_messages_for :linkset, :object_name => "gem" %>
<%= form_for @rubygem.linkset, :url => rubygem_url(@rubygem), :method => :put do |form| %>
  <div class="url_field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>
  <div class="url_field">
    <%= form.label :docs %>
    <%= form.text_field :docs %>
  </div>
  <div class="url_field">
    <%= form.label :wiki %>
    <%= form.text_field :wiki %>
  </div>
  <div class="url_field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>
  <div class="url_field">
    <%= form.label :bugs %>
    <%= form.text_field :bugs %>
  </div>
  <%= form.submit t('update'), :data => {:disable_with => t('form_disable_with')} %>
<% end %>

app/views/rubygems/index.html.erb
<% @title = t('.title') %>
<% @subtitle = t('.subtitle', :prefix => content_tag(:em, @letter)).html_safe %>
<div class="directory border">
  <ol>
    <% ("A".."Z").each do |letter| %><li><%= link_to(letter, rubygems_path(:letter => letter)) %></li><% end %>
  </ol>
</div>
<p class="entries">
  <%= page_entries_info @gems, :entry_name => 'gem', :model => 'gem' %>
</p>
<div class="gems border">
  <ol>
    <%= render @gems %>
  </ol>
</div>
<%= will_paginate @gems %>

app/views/rubygems/show.html.erb
<% @title = @rubygem.name %>
<% @subtitle = @latest_version.try(:slug) %>

<%= content_for :head, auto_discovery_link_tag(:atom, rubygem_versions_path(@rubygem, format: "atom"), {title: "#{@rubygem.name} Version Feed"}) %>

<% if @rubygem.versions.count.zero? %>
  <p><%= t '.not_hosted_notice' %></p>
<% else %>
  <% if @latest_version.indexed %>
    <div id="markup">
      <%= simple_markup(@latest_version.info) %>
    </div>

    <div class="border">
      <%= render :partial => "rubygems/clippy", :locals => { :embed => "clippy", :text => @latest_version.to_install } %>
      <div class="install">
        <div class="instructions"><strong><%= t '.install' %></strong><span><%= @latest_version.to_install %></span></div>
      </div>
    </div>
  <% else %>
    <p><%= t('.yanked_notice', :more_info_link => link_to(t('.yank_info_link_text'), "http://help.rubygems.org/faqs/gemcutter/removing-a-published-rubygem")).html_safe %></p>
  <% end %>

  <div class="border">
    <div class="meta">
      <div class="admin">
        <%= link_to t('edit'), edit_rubygem_path(@rubygem), :id => "edit" if @rubygem.owned_by?(current_user) %>
        <!-- 
          Not ready yet on the Gittip side! :-(
          https://github.com/gittip/www.gittip.com/issues/1591
        <%= gittip_link(@rubygem) if @rubygem.gittip_enabled? %>
        -->
        <%= download_link(@latest_version) %>
        <%= documentation_link(@latest_version, @rubygem.linkset) %>
        <%= badge_link(@rubygem) %>
        <%= subscribe_link(@rubygem) if @latest_version.indexed %>
        <%= unsubscribe_link(@rubygem) %>
        <%= atom_link(@rubygem) %>
      </div>

      <% if @latest_version.indexed %>
        <div class="who">
          <div class="authors info-item">
            <% if @latest_version.authors.present? %>
              <h5><%= t '.authors_header' %></h5>
              <p><%= @latest_version.authors %></p>
            <% end %>
          </div>

          <% unless Rails.env.recovery? %>
            <div class="downloads counter" data-href="<%= api_v1_download_path(@latest_version.full_name, :format => 'json') %>">
              <span>
                <%= t('stats.show.total_downloads', :count => content_tag(:strong, number_with_delimiter(@rubygem.downloads))).html_safe %>
              </span>
              <span>
                <%= t('.downloads_for_this_version', :count => content_tag(:strong, number_with_delimiter(@latest_version.downloads_count))).html_safe %>
              </span>
            </div>
          <% end %>

          <% if @rubygem.owners.present? %>
            <div class="owners info-item">
              <h5><%= t '.owners_header' %></h5>
              <p><%= links_to_owners(@rubygem) %></p>
            </div>
          <% end %>

          <% if @latest_version.licenses.present? %>
            <div class="licenses info-item">
              <h5><%= t '.licenses_header' %></h5>
              <p><%= formatted_licenses @latest_version.licenses %></p>
            </div>
          <% end %>
        </div>

        <% if @rubygem.linkset.present? %>
          <div class="links">
            <h5><%= t '.links.header' %></h5>
            <%= link_to_page t('.links.home'), @rubygem.linkset.home %>
            <%= link_to_page t('.links.code'), @rubygem.linkset.code %>
            <%= link_to_page t('.links.docs'), @rubygem.linkset.docs %>
            <%= link_to_page t('.links.wiki'), @rubygem.linkset.wiki %>
            <%= link_to_page t('.links.mail'), @rubygem.linkset.mail %>
            <%= link_to_page t('.links.bugs'), @rubygem.linkset.bugs %>
          </div>
        <% end %>

        <div class="bundler">
          <h5><%= t '.bundler_header' %></h5>
          <%= render :partial => "rubygems/clippy", :locals => { :embed => "github_clippy", :text => @latest_version.to_bundler } %>
          <pre><code><%= @latest_version.to_bundler %></code></pre>
        </div>
      <% end %>

    <% if @versions.present? %>
      <div class="versions">
        <h5><%= t '.versions_header' %></h5>
        <ol>
          <%= render @versions %>
        </ol>
        <% if show_all_versions_link?(@rubygem) %>
          <%= link_to t('.show_all_versions', :count => @rubygem.versions.count), rubygem_versions_url(@rubygem), :class => "more" %>
        <% end %>
      </div>
    <% end %>

      <%= render :partial => "rubygems/dependencies", :locals => { :dependencies => @latest_version.dependencies.runtime } %>
      <%= render :partial => "rubygems/ruby_version", :locals => { :ruby_version => @latest_version.ruby_version } %>
      <%= render :partial => "rubygems/dependencies", :locals => { :dependencies => @latest_version.dependencies.development } %>

      <% if @latest_version.requirements.present? %>
        <div class="dependencies requirements_dependencies">
          <h5><%= t '.requirements_header' %></h5>
          <ol>
            <% Array(@latest_version.requirements).each do |requirement| %>
              <li><%= requirement %></li>
            <% end %>
          </ol>
        </div>
      <% end %>

    </div>
  </div>
<% end %>