config/routes.rb
Gemcutter::Application.routes.draw do
  ################################################################################
  # Root

  root :to => 'home#index'

  ################################################################################
  # API v1

  namespace :api do
    namespace :v1 do
      resource :api_key, :only => :show do
        put :reset
      end
      resources :profiles, :only => :show
      resources :downloads, :only => :index do
        get :top, :on => :collection
        get :all, :on => :collection
      end
      constraints :id => Patterns::ROUTE_PATTERN, :format => /json|xml|yaml/ do
        get 'owners/:handle/gems(.:format)', :to => 'owners#gems', :as => 'owners_gems', :constraints => {:handle => Patterns::ROUTE_PATTERN}

        # In Rails 3.1, the following line can be replaced with:
        # resources :downloads, :only => :show, :format => true
        get 'downloads/:id.:format', :to => 'downloads#show', :as => 'download'
        # In Rails 3.1, the next TWO lines can be replaced with:
        # resources :versions, :only => :show, :format => true do
        get 'versions/:id.:format', :to => 'versions#show', :as => 'version'
        resources :versions, :only => :show do
          member do
            # In Rails 3.1, the following line can be replaced with:
            # get :reverse_dependencies, :format => true
            get 'reverse_dependencies.:format', :to => 'versions#reverse_dependencies', :as => 'reverse_dependencies'
          end

          member do
            get 'latest.json', :to => 'versions#latest', :as => 'latest'
          end

          # In Rails 3.1, the next TWO lines can be replaced with:
          # resources :downloads, :only => :show, :controller => 'versions/downloads', :format => true do
          get 'downloads.:format', :to => 'versions/downloads#index', :as => 'downloads'
          resources :downloads, :only => :index, :controller => 'versions/downloads' do
            collection do
              # In Rails 3.1, the following line can be replaced with:
              # get :search, :format => true
              get 'search.:format', :to => 'versions/downloads#search', :as => 'search'
            end
          end
        end
      end

      resources :dependencies, :only => :index

      resources :rubygems, :path => 'gems', :only => [:create, :show, :index], :id => Patterns::LAZY_ROUTE_PATTERN, :format => /json|xml|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank
          put :unyank
        end
        constraints :rubygem_id => Patterns::ROUTE_PATTERN do
          resource :owners, :only => [:show, :create, :destroy]
        end
      end

      resource :activity, :only => [], :format => /json|xml|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, :only => :show

      resources :web_hooks, :only => [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  ################################################################################
  # API v0

  scope :to => 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset'

    post 'gems'
    get  'gems/:id.json'

    scope :path => 'gems/:rubygem_id' do
      put  'migrate'
      post 'migrate'
      get    'owners(.:format)'
      post   'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI

  resource  :search,    :only => :show
  resource  :dashboard, :only => :show
  resources :profiles,  :only => :show
  resource  :profile,   :only => [:edit, :update]
  resources :stats,     :only => :index, :constraints => RecoveryMode

  resources :rubygems, :only => :index, :path => 'gems' do
    constraints :rubygem_id => Patterns::ROUTE_PATTERN do
      resource  :subscription, :only => [:create, :destroy]
      resources :versions,     :only => :index
    end
  end

  constraints :id => Patterns::ROUTE_PATTERN do
    resources :rubygems, :path => 'gems', :only => [:show, :edit, :update] do

      constraints :rubygem_id => Patterns::ROUTE_PATTERN do
        resources :versions, :only => :show
      end
    end
  end

  ################################################################################
  # Clearance Overrides

  resource :session, :only => [:create, :destroy]

  match 'sign_out' => 'sessions#destroy', :via => :delete, :as => 'sign_out'

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:create, :edit, :update]
  end

end

app/views/layouts/_feeds.html.erb
<% if signed_in? %>
  <%= atom_feed_link t(:feed_subscribed), dashboard_url(:api_key => current_user.api_key, :format => :atom) %>
<% end %>

<%= atom_feed_link t(:feed_latest), 'http://feeds.feedburner.com/gemcutter-latest' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="google-site-verification" content="AuesbWQ9MCDMmC1lbDlw25RJzyqWOcDYpuaCjgPxEZY" />
    <link rel="apple-touch-icon" href="/touch-icon-iphone.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/touch-icon-ipad.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="/touch-icon-iphone4.png" />
    <link rel="fluid-icon" href="/fluid-icon.png"/>
    <link rel="search" type="application/opensearchdescription+xml" title="<%=t :title %>" href="/opensearch.xml">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <%= stylesheet_link_tag "reset", "960", "screen", :cache => true %>
    <!--[if IE 7]>
      <%= stylesheet_link_tag "ie7" %>
    <![endif]-->
    <%= render "layouts/feeds" %>
    <%= csrf_meta_tag %>
    <%= yield :head %>
    <title><%= page_title %></title>
  </head>
  <body>
    <div class="container_12">
      <div class="prefix_1 grid_4 header">
        <h1><%= link_to t(:title), root_url, :title => "Home" %></h1>
      </div>
      <div class="grid_6 suffix_1 nav">
        <div id="nav-cap">
          <div id="nav">
            <% if signed_in? %>
                <div id="user-info">
                  <a href="<%= profile_path(current_user.display_id) %>">
                    <%= gravatar(32, "user_gravatar") %>
                    <span><%= truncate(current_user.name) %></span>
                  </a>
                </div>
                <ul id="signed_in">
                  <li id="all-gems"><%= link_to t('.header.all_gems'), rubygems_url %></li>
                  <li id="dashboard"><%= link_to t('.header.dashboard'), dashboard_url %></li>
                  <li id="sign-out"><%= link_to t('.header.sign_out'), sign_out_path, :method => :delete %></li>
                </ul>
            <% else %>
              <ul id="signed_out">
                <li id="all-gems"><%= link_to "all gems", rubygems_url %></li>

                <li id="sign-in">
                  <a href="<%= ssl_url_for :controller => 'clearance/sessions',
                                           :action     => 'new' %>"><%= t('.header.sign_in') %></a>
                </li>

                <li id="sign-up">
                  <a href="<%= ssl_url_for :controller => 'clearance/users',
                                           :action     => 'new' %>"><%= t('.header.sign_up') %></a>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
        <%= form_tag search_url, :id => "main-search", :method => :get do %>
          <%= text_field_tag :query, params[:query], :placeholder => "Search gems&hellip;".html_safe %>
          <%= submit_tag 'Search', :id => 'search_submit', :name => nil %>
        <% end %>
      </div>
      <div class="prefix_1 grid_10 suffix_1 main">
        <% flash.each do |name, msg| %>
          <div id="flash-border">
            <div id="flash_<%= name %>"><span><%= msg %></span></div>
          </div>
        <% end %>
        <%= render :partial => "announcements/announcement_for_all" %>
        <% if content_for?(:fold) %>
          <div class="fold">
            <%= yield :fold %>
          </div>
        <% end %>
        <div class="info clearfix">
          <div class="title">
            <% if @title %>
              <h2><%= link_to @title, @title_url %></h2>
            <% end %>
            <% if @subtitle %>
              <h3><%= @subtitle.html_safe %></h3>
            <% end %>
            <%= yield :title %>
          </div>
          <%= yield %>
        </div>
      </div>
      <div class="prefix_1 grid_10 suffix_1 footer">
        <ul class="major">
          <li><%= link_to t('.footer.help'), t(:help_url) %></li>
          <li><%= link_to t('.footer.guides'), "http://guides.rubygems.org"  %></li>
          <li><%= link_to t('.footer.blog'), "http://blog.rubygems.org" %></li>
          <li><%= link_to t('.footer.contribute'), "http://guides.rubygems.org/contributing/"  %></li>
        </ul>
        <ul class="minor">
          <li><%= link_to t('.footer.mobile'), "http://m.rubygems.org" %></li>
          <li><%= link_to t('.footer.status'), "http://status.rubygems.org" %></li>
          <li><%= link_to t('.footer.uptime'), "http://uptime.rubygems.org" %></li>
          <li><%= link_to t('.footer.source_code'), "http://github.com/rubygems/rubygems.org" %></li>
          <li><%= link_to t('.footer.discussion_forum'), "http://groups.google.com/group/rubygems-org" %></li>
          <li><%= link_to t('.footer.statistics'), stats_url %></li>
          <li><%= link_to t('.footer.about'), page_url("about") %></li>
        </ul>


        <ul class="sponsors">

            <div class="row">

              <li id="rubycentral" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Supported by', 'http://rubycentral.org', :title => 'Ruby Central' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/rubycentral.png', :alt => 'Ruby Central'), "http://rubycentral.org", :class => 'bottom' %>
                </div>
              </li>

              <li id="bluebox" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Hosted by', 'http://bluebox.net', :title => 'Bluebox' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/bluebox.png', :alt => 'Bluebox'), "http://bluebox.net", :class => 'bottom' %>
                </div>
              </li>

              <li id="thoughtbot" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Designed by', 'http://thoughtbot.com', :title => 'Thoughtbot' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/thoughtbot.png', :alt => 'Thoughtbot'), "http://thoughtbot.com", :class => 'bottom' %>
                </div>
              </li>

              <li id="dnsimple" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Resolved with', 'http://dnsimple.com', :title => 'dnsimple' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/dnsimple.png', :alt => 'dnsimple'), "http://dnsimple.com", :class => 'bottom' %>
                </div>
              </li>

            </div> <!-- .row -->

            <div class="row">

              <li id="newrelic" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Optimized by', 'http://newrelic.com', :title => 'New Relic' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/newrelic.png', :alt => 'New Relic'), "http://newrelic.com", :class => 'bottom' %>
                </div>
              </li>

              <li id="gauges" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Tracking by', 'http://gaug.es', :title => 'Gauges' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/gauges.png', :alt => 'Gauges'), "http://gaug.es", :class => 'bottom' %>
                </div>
              </li>

              <li id="stillalive" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Monitored by', 'http://stillalive.com', :title => 'StillAlive' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/stillalive_hover.png', :alt => 'StillAlive'), "http://stillalive.com", :class => 'bottom' %>
                  <%= link_to image_tag('sponsors/stillalive.png', :alt => 'StillAlive'), "http://stillalive.com", :class => 'top' %>
                </div>
              </li>

              <li id="runscope" class="sponsor">
                <span class="sponsor_text"><%= link_to 'Monitored by', 'https://www.runscope.com/t/rubygems', :title => 'Runscope' %></span>
                <div class="sponsor_logo">
                  <%= link_to image_tag('sponsors/runscope.png', :alt => 'Runscope'), "https://www.runscope.com/t/rubygems", :class => 'bottom' %>
                </div>
              </li>

          </div> <!-- .row -->

        </ul>


      </div>
    </div>
    <%= javascript_include_tag "jquery.min", "jquery.easing.1.3", "jquery.color", "jquery_ujs", "announcements", "application", :cache => true %>
    <%= yield :javascript %>
    <script type="text/javascript">
      var _gauges = _gauges || [];
      (function() {
        var t   = document.createElement('script');
        t.type  = 'text/javascript';
        t.async = true;
        t.id    = 'gauges-tracker';
        t.setAttribute('data-site-id', '4eab0ac8613f5d1583000005');
        t.src = '//secure.gaug.es/track.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(t, s);
      })();
    </script>
  </body>
</html>